FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8089
CMD ["locust", "-f", "locustfile.py", "--web-port", "8089", "--host", "http://reverse-proxy"]
