FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html
COPY extensions.css /usr/share/nginx/html/extensions.css
COPY extensions.js /usr/share/nginx/html/extensions.js
EXPOSE 80
